# Nombre de la aplicaci贸n
spring:
  application:
    name: biblioteca-crud-1

# Configuraci贸n del datasource
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca2024
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# Configuraci贸n de JPA e Hibernate
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Configuraci贸n del servidor
server:
  port: 8080
